package com.excitel.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
@DynamoDBTable(tableName = "customer-coupon-table")
public class CustomerCoupon {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "MobileNumber")
    private String mobileNumber;

    @NotEmpty
    @NotNull
    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "CouponID")
    private String couponID;

    @NotNull
    @DynamoDBAttribute(attributeName = "ActivationDate")
    private String activationDate;

    @NotNull
    @DynamoDBAttribute(attributeName = "CouponStatus")
    private String couponStatus;

    @NotNull
    @DynamoDBAttribute(attributeName = "CustomerCouponID")
    private String customerCouponId;
}
